blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path("", render_posts, name="posts"),
    path("<int:post_id>", post_detail, name="post_detail"),
   
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.title

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images/")
    url = URLField(blank=True)
    date = DateField(default=date.today)

    def __str__(self) -> str:
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, "home.html", {"projects": projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{ post.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h3>

    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">

    <div class="my-4">
        <p>{{ post.description|safe }}</p>
    </div>
</div>
    
{% endblock content %}
    
    

blog/templates/posts.html
{% extends 'layout.html' %}


{% block content %}
<h1>Posts</h1>

    {% for post in posts %}

       <div class="p-3">
        <div class="card card-body bg-black">
            <div class="row">
                 <div class="col-3">
                     <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                 </div>
                 <div class="col-9">
                     <h2>{{ post.title }}</h2>
                     <p>{{ post.description|striptags|truncatechars:100 }}</p>
                     <p>{{ post.date|date:'M d Y'|upper }}</p>
             
 
                     <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{ post.title }}</a>
                 </div>
            </div>
             
             
        </div>
       </div>
        
    {% endfor %}
{% endblock content %}
    

portfolio/templates/home.html
{% extends 'layout.html' %}


{% block content %}

{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/profile.jpg' %}" class="img-fluid">
    </div>

    <div class="col-md-8 my-auto">
        <h1>I am <strong>Carlos Jiménez</strong></h1>
        <h3>I am a Python FullStack Developer</h3>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque natus, 
            similique eum culpa fuga aut exercitationem veniam illo mollitia eligendi ipsam dignissimos 
            molestias officia itaque asperiores voluptates deleniti blanditiis modi voluptas magnam 
            ipsa, eos odit. Nostrum quisquam ad libero, quibusdam iure corrupti pariatur tempora vitae 
            mollitia nihil cum ea laboriosam quas similique iste explicabo perferendis, dolor deserunt 
            molestiae ex! Dolorem explicabo fugiat itaque repellendus nobis voluptas a nihil voluptatibus 
            porro amet. Iste sunt labore ut explicabo eveniet deleniti expedita! Suscipit quia quae porro dolorem 
            aspernatur amet, molestiae vero incidunt maiores ut, explicabo, aliquam quisquam quo quas nam 
            dolores quibusdam numquam.</p>
        <a href="{% static 'portfolio/Profile.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
    </div>
</header>

<!-- Porfolio Section -->
<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, aperiam?</p>
  
    {% for project in projects %}

    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <img src="{{project.image.url }}" class="card-img-top" />
    
            <div class="card-body">
    
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
        
                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Visit the
                    Project</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}
</div>
  
  
{% endblock %}
    
    

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"> -->
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock content %}
    </div>
    

    <!-- <footer>Footer</footer> -->
    {% include 'partials/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/partials/footer.html
{% load static %}

<footer class="bg-black text-light pt-4 pb-3">	

    <div class="container text-center text-md-left">

        <div class="row text-center text-md-left">

            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-info">About Us</h5>
                    <hr class="mb-4">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt labore et dolore magna aliqua. Ut enim minim veniam,  nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                
            </div>


            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-info">Make Money</h5>
                    <hr class="mb-4">
            <p>
                <a href="#" class="text-light" style="text-decoration: none;"> Sell products on our Website</a>
            </p>
            <p>
                <a href="#" class="text-light" style="text-decoration: none;"> Advertise Your Products</a>
            </p>
            <p>
                <a href="#" class="text-light" style="text-decoration: none;">Become an Affiliates</a>
            </p>
            <p>
                <a href="#" class="text-light" style="text-decoration: none;"> Self-Publish</a>
            </p>
            </div>

            <div class="col-md-4 col-lg-3 col-xl-4 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-info" >Contact</h5>
                    <hr class="mb-4">
                <p>
                    <i class="fas fa-home mr-3"></i>Castilla, Piura, Perú
                </p>
                <p>
                    <i class="fas fa-envelope mr-3"></i>carloshernanjimenez876@gmail.com
                </p>
                <p>
                    <i class="fas fa-phone mr-3"></i>+51 961160436
                </p>
                
            </div>
            
        </div>

        <hr class="mb-4">
        <div class=" row d-flex justify-content-center">
                <div>
                    <p>	Copyright ©2020 All rights reserved by:
                        <a href="#" style="text-decoration: none;">
                            <strong class="text-info">carjiso</strong>
                        </a>
                    </p>
                </div>
        </div>
            <div class="row d-flex justify-content-center">
                <div class="text-center ">

                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/carlos.jimenezdominguez.3" class="text-light" target="_blank"><i class="fab fa-facebook"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://twitter.com/home?lang=es" class= "text-light" target="_blank"><i class="fab fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/carlos-jim%C3%A9nez-784005208/" class=" text-light" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.youtube.com/channel/UCrJv_c_2eV5u2Mmtaf224uA" class=" text-light" target="_blank"><i class="fab fa-youtube"></i></a>
                        </li>
                    </ul>
                    
                </div>
                
            </div>
            
        </div>

    </div>
</footer>

portfolio/templates/partials/navbar.html
{% load static %}

  <nav class="navbar navbar-expand-lg navbar-dark bg-black">
  
    <div class="container">

      <a class="navbar-brand fw-bold fst-italic" href="/">Carjiso</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/Profile.pdf' %}"
            target="_blank"
            >Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

 